### ISSUE TITLE
is `initial_features` used?

### ISSUE THREAD

**Issue by audiracmichelle** [NSAPH-Projects/topological-equivariant-networks#67]
in class Lifter

**Comment by audiracmichelle** [comment]
@ekarais do you happen to know where initial_features is used for create_dataset?

**Comment by ekarais** [comment]
@audiracmichelle, good catch, it is not used

**Comment by audiracmichelle** [comment]
got it! is it used at another point in training?

**Comment by ekarais** [comment]
Yes, it is used to initialize cell features in the forward pass
