### ISSUE TITLE
Standardize create dataset for compatible MLFlow of spatial_cc and qm9_cc

### ISSUE THREAD

**Issue by audiracmichelle** [NSAPH-Projects/topological-equivariant-networks#69]

**Comment by audiracmichelle** [comment]
`process_qm9_dataset` becomes unnecessary when the existence of the `datapath` is tracked my InMemoryDataset

**Comment by audiracmichelle** [comment]
lifter and Combinatorial Complex defined in `lift_qm9_to_cc` should be incorporated into QM9_CC object

**Comment by audiracmichelle** [comment]
change CombinatorialComplexData().from_json() to CombinatorialComplexData.from_ccdict()

**Comment by audiracmichelle** [comment]
make datasets compatible with the torch geometric API (pt caching):

- Thd create dataset script for both the Geospatial and QM9 CCs is analogous and supports the Hydra config system. The datasets are stored under the data/ folder and the root directory depends on the configuration.
- The data inputs logic has been reorganized for better data organization.
- Implements internal storage as as concatenated cell membership list and slices which contains the lengths.
- Adds cell_list method to data object for easily converting to cell list.
- collate logic is no longer part of a custom collator but it is builtin in the new InMemoryCCDataset class. Both the Geospatial and QM9 CCs are of this type.

Update the notebook for creating the Geospatial dataset and figures.

Make the Geospatial raw dataset  downloadable from Github.

**Comment by mauriciogtec** [comment]
Fixed in #75
